package pesansingkat;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Admin extends javax.swing.JFrame {

    public Member member;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    Database DB;
    
    public Admin(Member member) {
        initComponents();
        this.member = member;
        DB = new Database();
        DB.start();
        con = DB.koneksi;
        stat = DB.statement;
        setVisible(true);
        getData();
    }
    
    public void getData(){
        DefaultTableModel modelPesan = (DefaultTableModel)pesanTable.getModel();
        DefaultTableModel modelUser = (DefaultTableModel)memberTable.getModel();
        try {
                sql = "SELECT * FROM pesan";
                rs = stat.executeQuery(sql);
                modelPesan.setRowCount(0);
                while(rs.next()){                    
                    modelPesan.addRow(new Object[]{rs.getInt("id"),rs.getString("dari"),rs.getString("untuk"),rs.getString("pesan"), rs.getString("date")});
                }
                
                sql = "SELECT * FROM member WHERE status="+"'"+0+"'";
                rs = stat.executeQuery(sql);
                modelUser.setRowCount(0);
                while(rs.next()){                    
                    modelUser.addRow(new Object[]{rs.getInt("id"),rs.getString("nama"),rs.getString("email"),rs.getString("password"), "user"});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesanTable = new javax.swing.JTable();
        deletePesanBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        deleteMemberBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        untukField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        pesanField = new javax.swing.JTextArea();
        kirimPesanBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keluarBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        pesanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Dari", "Untuk", "Pesan", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pesanTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 35, 371, 240);

        deletePesanBtn.setText("Delete");
        deletePesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePesanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletePesanBtn);
        deletePesanBtn.setBounds(318, 6, 63, 23);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 390, 290);

        jTabbedPane1.addTab("Pesan", jPanel1);

        jPanel2.setLayout(null);

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Email", "Passwrod", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(memberTable);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 42, 371, 240);

        deleteMemberBtn.setText("Delete");
        deleteMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemberBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteMemberBtn);
        deleteMemberBtn.setBounds(318, 11, 63, 25);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 390, 290);

        jTabbedPane1.addTab("Member", jPanel2);

        jPanel3.setLayout(null);

        jLabel3.setText("Untuk :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(35, 23, 35, 14);

        jLabel4.setText("Pesan :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(34, 58, 36, 14);
        jPanel3.add(untukField);
        untukField.setBounds(104, 20, 166, 20);

        pesanField.setColumns(20);
        pesanField.setRows(5);
        jScrollPane3.setViewportView(pesanField);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(104, 58, 166, 160);

        kirimPesanBtn.setText("Kirim");
        kirimPesanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kirimPesanBtnMouseClicked(evt);
            }
        });
        jPanel3.add(kirimPesanBtn);
        kirimPesanBtn.setBounds(215, 236, 55, 23);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 390, 290);

        jTabbedPane1.addTab("Kirim Pesan", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 30, 396, 316);

        jLabel1.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel1.setText("Admin Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 111, 24);

        keluarBtn.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        keluarBtn.setText("Keluar");
        keluarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarBtnMouseClicked(evt);
            }
        });
        getContentPane().add(keluarBtn);
        keluarBtn.setBounds(354, 8, 32, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimPesanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kirimPesanBtnMouseClicked
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");  
        LocalDateTime now = LocalDateTime.now(); 
        String dari = member.getNama();
        String pesan = pesanField.getText();
        String untuk = untukField.getText();
        String date = dtf.format(now).toString();
        
        try{
            sql = "INSERT into pesan(dari, untuk, pesan, date) VALUES (" + "'" +dari+ "'" + "," + "'" +untuk+ "'" + "," + "'" +pesan+ "'" + "," + "'" +date+ "'"+")";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Pesan Berhasil Di Kirim !!!");
            getData();
            untukField.setText(null);
            pesanField.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_kirimPesanBtnMouseClicked

    private void keluarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(this, "Anda Telah Logout !!!");
        LoginPage l = new LoginPage();
        l.setVisible(true);
    }//GEN-LAST:event_keluarBtnMouseClicked

    private void deletePesanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePesanBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelPesan = (DefaultTableModel)pesanTable.getModel();
        String idPesan = modelPesan.getDataVector().elementAt(pesanTable.getSelectedRow()).get(0).toString();
        try{
            sql = "DELETE FROM pesan WHERE id = '"+idPesan+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Pesan Berhasil Di Hapus !!!");
            getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deletePesanBtnActionPerformed

    private void deleteMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemberBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelPesan = (DefaultTableModel)memberTable.getModel();
        String idMember = modelPesan.getDataVector().elementAt(memberTable.getSelectedRow()).get(0).toString();
        try{
            sql = "DELETE FROM member WHERE id = '"+idMember+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Member Berhasil Di Hapus !!!");
            getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteMemberBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteMemberBtn;
    private javax.swing.JButton deletePesanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel keluarBtn;
    private javax.swing.JButton kirimPesanBtn;
    private javax.swing.JTable memberTable;
    private javax.swing.JTextArea pesanField;
    private javax.swing.JTable pesanTable;
    private javax.swing.JTextField untukField;
    // End of variables declaration//GEN-END:variables
}
