package pesansingkat;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class LoginPage extends javax.swing.JFrame {
    
    String email;
    String password;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    Database DB;
    Member member;
    
    public LoginPage() {
        initComponents();
        DB  = new Database();
        DB.start();
        con = DB.koneksi;
        stat = DB.statement;
        member = new Member();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        registrasiBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Login Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(98, 11, 100, 24);

        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 56, 24, 14);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 94, 46, 14);
        getContentPane().add(emailField);
        emailField.setBounds(125, 53, 161, 20);
        getContentPane().add(passField);
        passField.setBounds(125, 91, 161, 20);

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(229, 151, 57, 23);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(37, 151, 51, 23);

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 8)); // NOI18N
        jLabel4.setText("Silahkan Login untuk menggunakan aplikasi PesanSingkat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 225, 215, 10);

        registrasiBtn.setText("Registrasi");
        registrasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrasiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrasiBtn);
        registrasiBtn.setBounds(94, 151, 129, 23);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        email = emailField.getText();
        password = passField.getText();
        try{
            sql = "SELECT * FROM member WHERE email='"+email+"' AND password='"+password+"'";
            rs = stat.executeQuery(sql);   
            if(rs.next()){
                if(email.equals(rs.getString("email")) && password.equals(rs.getString("password"))){
                    member.setId(rs.getInt("id"));
                    member.setNama(rs.getString("nama"));
                    member.setEmail(rs.getString("email"));
                    member.setPass(rs.getString("password"));
                    member.setStatus(rs.getInt("status"));
                    JOptionPane.showMessageDialog(null, "Login Berhasil !!!");
                    this.dispose();
                    if(rs.getInt("status") == 1){
                        Admin admin = new Admin(this.member);
                    }else{
                        MemberPage member = new MemberPage(this.member);
                    }
                }
            }else{
                    JOptionPane.showMessageDialog(null, "wrong username or password");
                }
        }catch (Exception e){
                JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registrasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrasiBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Registrasi l = new Registrasi();
        l.setVisible(true);
    }//GEN-LAST:event_registrasiBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton registrasiBtn;
    // End of variables declaration//GEN-END:variables
}
