package pesansingkat;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MemberPage extends javax.swing.JFrame {
    public Member member;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    Database DB;

    public MemberPage(Member member) {
        initComponents();
        this.member = member;
        DB = new Database();
        DB.start();
        con = DB.koneksi;
        stat = DB.statement;
        setVisible(true);
        member = new Member();
        getData();
    }

    public void getData(){
        DefaultTableModel modelInbox = (DefaultTableModel)pesanMasukTable.getModel();
        DefaultTableModel modelOutbox = (DefaultTableModel)pesanKeluarTable.getModel();
        try {
                sql = "SELECT * FROM pesan WHERE untuk="+"'"+member.getNama()+"'";
                rs = stat.executeQuery(sql);
                modelInbox.setRowCount(0);
                while(rs.next()){                    
                    modelInbox.addRow(new Object[]{rs.getInt("id"),rs.getString("dari"),rs.getString("pesan"),rs.getString("date")});
                }
                
                sql = "SELECT * FROM pesan WHERE dari="+"'"+member.getNama()+"'";
                rs = stat.executeQuery(sql);
                modelOutbox.setRowCount(0);
                while(rs.next()){                    
                    modelOutbox.addRow(new Object[]{rs.getInt("id"),rs.getString("untuk"),rs.getString("pesan"),rs.getString("date")});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesanMasukTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pesanKeluarTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        penerimaField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        pesanField = new javax.swing.JTextArea();
        kirimBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel1.setText("Member Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 126, 24);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(326, 15, 65, 23);

        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel2.setText("Pesan Masuk");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(144, 11, 93, 19);

        pesanMasukTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Dari", "Pesan", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pesanMasukTable);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 36, 356, 214);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 260);

        jTabbedPane2.addTab("Pesan Masuk", jPanel4);

        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel3.setText("Pesan Keluar");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(142, 11, 93, 19);

        pesanKeluarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Untuk", "Pesan", "Date"
            }
        ));
        jScrollPane2.setViewportView(pesanKeluarTable);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 36, 356, 214);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 260);

        jTabbedPane2.addTab("Pesan Keluar", jPanel5);

        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel4.setText("Kirim Pesan");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(149, 11, 83, 19);

        jLabel5.setText("Penerima :");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(22, 39, 51, 14);

        jLabel6.setText("Pesan :");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(22, 67, 36, 14);
        jPanel6.add(penerimaField);
        penerimaField.setBounds(83, 36, 166, 20);

        pesanField.setColumns(20);
        pesanField.setRows(5);
        jScrollPane3.setViewportView(pesanField);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(83, 67, 166, 129);

        kirimBtn.setText("Kirim");
        kirimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimBtnActionPerformed(evt);
            }
        });
        jPanel6.add(kirimBtn);
        kirimBtn.setBounds(194, 207, 55, 23);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel3);
        jPanel3.setBounds(0, 0, 380, 260);

        jTabbedPane2.addTab("Kirim Pesan", jPanel6);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(10, 44, 381, 289);

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimBtnActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");  
        LocalDateTime now = LocalDateTime.now();  
        String pesan = pesanField.getText();
        String untuk = penerimaField.getText();
        String dari = member.getNama();
        String date = dtf.format(now).toString();
        try{
            sql = "INSERT into pesan(dari, untuk, pesan, date) VALUES (" + "'" +dari+ "'" + "," + "'" +untuk+ "'" + "," + "'" +pesan+ "'" + "," + "'" +date+ "'"+")";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Pesan Berhasil Di Kirim !!!");
            getData();
            penerimaField.setText(null);
            pesanField.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_kirimBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(this, "Anda Telah Logout !!!");
        LoginPage l = new LoginPage();
        l.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton kirimBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField penerimaField;
    private javax.swing.JTextArea pesanField;
    private javax.swing.JTable pesanKeluarTable;
    private javax.swing.JTable pesanMasukTable;
    // End of variables declaration//GEN-END:variables
}
